version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"