deploy:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - name: Deploy to Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: kabalfrontend-pr-${{ github.event.number }}
        images: |
          kabaltest.azurecr.io/kabalfrontend:pr-${{ github.event.number }}
        slot-name: pr-${{ github.event.number }}
        resource-group: pageup
        azure-container-registry: kabaltest
        multi-container-config-file: |
          {
            "version": "1.0",
            "content": {
              "docker": [
                {
                  "name": "kabalfrontend",
                  "image": "kabaltest.azurecr.io/kabalfrontend:pr-${{ github.event.number }}",
                  "ports": [
                    {
                      "protocol": "tcp",
                      "port": "3000"
                    }
                  ]
                }
              ]
            }
          }